### ISSUE TITLE
preferredNetworks

### ISSUE THREAD

**Issue by yangzhiqing001** [SteeltoeOSS/Samples#37] opened 2018-03-08 14:05 UTC
spring.cloud.inetutils.preferredNetworks[0]=^192\.168 
spring.cloud.inetutils.ignored-interfaces[0]=eth0
or
"cloud": {
      "inetutils": {
        "preferredNetworks": [ "^192" ]
      }
    }

The above some lines did not worded
Can you help for it ?

**Comment by yangzhiqing001** [comment] 2018-05-23 12:42
ifconfig -a
eth2      Link encap:Ethernet  HWaddr 00:50:56:B3:7E:9B  
          inet addr:172.16.118.1  Bcast:172.16.118.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:feb3:7e9b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5279275 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4629500 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1793212014 (1.6 GiB)  TX bytes:708143077 (675.3 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:22702 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22702 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1271292 (1.2 MiB)  TX bytes:1271292 (1.2 MiB)

this is my network config.
when i use this config register to the eureka server.
i found that the registered IP address is 127.0.0.1.i think thas is a wrong address

**Comment by TimHess** [comment] 2018-05-23 14:29
Closing this as a duplicate of https://github.com/SteeltoeOSS/Discovery/issues/26

**Closed by TimHess** 2018-05-23 14:29 UTC
Labels: unscheduled
